AMaoChen0110/Unseat

- base.js
- style.css
> 新增功能：收件進度條第2版

- index.html
- style.css
> 新增資訊區塊與樣式調整，改善使用者介面與互動效果

- base.js
- index.html
- style.css
> 新增收件數顯示與進度條，改善使用者介面與資訊呈現

- base.js
> 改善收件數顯示格式，新增數字格式化與樣式調整

- index.html
新增Google Analytics追蹤代碼以提升網站數據分析能力
> 新增Google Analytics追蹤代碼以提升網站數據分析能力

- index.html
調整重要消息的顯示內容與格式，更新認證地點的描述以提供更清晰的資訊
> 調整重要消息的顯示內容與格式，更新認證地點的描述以提供更清晰的資訊

- base.js
- index.html
修正收件數未更新時的顯示文字，新增結構化數據標記以改善SEO與資訊呈現
> 修正收件數未更新時的顯示文字，新增結構化數據標記以改善SEO與資訊呈現

- base.js
- index.html
調整基隆市林沛祥的起始天數為-5，更新顯示為第-6天，並更新base.js的版本號
> 調整基隆市林沛祥的起始天數為-5，更新顯示為第-6天，並更新base.js的版本號

- style.css
> 新增背景漸層及進度條樣式，提升視覺效果與可讀性

- style.css
> 調整標題的上邊距，改善排版效果

- base.js
- index.html
- personData.json
更新 base.js 的日期計算邏輯，移除不必要的基準日期定義，並修正計算當前天數的方式
> 更新 base.js 的日期計算邏輯，移除不必要的基準日期定義，並修正計算當前天數的方式

- scripts/floatingMenu.js
新增觸控支援，改善浮動按鈕及面板的拖曳功能，優化樣式及事件處理
> 新增觸控支援，改善浮動按鈕及面板的拖曳功能，優化樣式及事件處理

- index.html
新增網站標誌至 Open Graph 元資料，以增強網站識別度
> 新增網站標誌至 Open Graph 元資料，以增強網站識別度

- scripts/floatingMenu.js
> 在觸控移動事件中新增預防畫面滑動的功能

- index.html
- scripts/main.js
- styles/style.css
> feat: 加上篩選與排序功能

- index.html
- scripts/main.js
- styles/style.css
> feat: 新增排序圖示切換功能與樣式調整

- ckfinder.html
- index.html
- scripts/main.js
> fix: 更新腳本版本與收件統計顯示文字

- reasonsRecall.html
fix: 更新 og:title 和 og:description 以反映正確的內容
> fix: 更新 og:title 和 og:description 以反映正確的內容

- scripts/main.js
- styles/style.css
> feat: 更新門檻顯示文字及調整樣式，優化進度條外觀

- complimentSquad.html
- index.html
- reasonsRecall.html
- scripts/complimentSquad.js
- scripts/main.js
- styles/complimentSquad.css
> feat: 更新網站標題及描述，新增誇誇計數器功能及樣式

- ckfinder.html
> feat: 新增誇誇計數器連結至浮動面板列表

- complimentSquad.html
> fix: 修正樣式表連結路徑

- scripts/main.js
> feat: 更新進度顯示文字，當數量為零時顯示「統計中」

- ckfinder.html
- complimentSquad.html
- index.html
- reasonsRecall.html
> feat: 新增「罷免選區整合網站」連結至多個頁面

- complimentSquad.html
- scripts/complimentSquad.js
- styles/complimentSquad.css
> fix: 誇誇報表手機跑版 & 重新取得報表圖片會重複

- index.html
- scripts/main.js
- styles/style.css
> feat: 加上目標、門檻、時間排序

- 419ProtestEvent.html
- ckfinder.html
- complimentSquad.html
- index.html
- indexUat.html
- reasonsRecall.html
- scripts/RecallPopupWeekend.js
> feat: 更新活動時間及新增連署地圖連結

- 419ProtestEvent.html
> feat: 更新開放進場時間標籤為「開放進場連署」

- scripts/main.js
> feat: 優化進度條顯示邏輯，新增進度條文本提示

- scripts/RecallPopupWeekend.js
> fix: 修正苗栗罷免宣講的地點資訊，新增詳細地址

- scripts/main.js
- styles/style.css
> fix: 更新持續收件中標籤文字，調整樣式以改善顯示效果

- index.html
- scripts/main.js
> feat: 時間排序按照比例排序

- index.html
fix: 注釋掉不必要的RecallPopupWeekend樣式和腳本引用
> fix: 注釋掉不必要的RecallPopupWeekend樣式和腳本引用

- personData.json
> fix: 調整桃園市牛煦庭的總天數至正確值

- personData.json
> fix: 調整桃園市呂玉玲的總天數至正確值

- scripts/RecallPopupWeekend.js
> fix: 新增點擊圖片關閉彈出層的功能

- scripts/RecallPopupWeekend.js
- styles/RecallPopupWeekend.css
fix: 調整彈出層關閉按鈕位置及樣式，並更新旋轉木馬容器結構
> fix: 調整彈出層關閉按鈕位置及樣式，並更新旋轉木馬容器結構

- index.html
- scripts/main.js
- styles/style.css
feat: 新增告急專區及跑馬燈功能，顯示收件進度與緊急通知
> feat: 新增告急專區及跑馬燈功能，顯示收件進度與緊急通知

- index.html
> fix: 更新主程式腳本版本至20250418

- scripts/main.js
> fix: 調整區域名稱格式，移除選區標記

- index.html
- indexUat.html
- scripts/main.js
> fix: 更新主程式腳本版本參數，修正急迫資料渲染邏輯

- indexUat.html
- scripts/mainUat.js
- styles/styleUat.css
> feat: 新增告急專區及相關樣式，優化收件進度顯示

- indexUat.html
> fix: 更新主程式腳本引用，修正檔案名稱錯誤

- indexUat.html
- scripts/mainUat.js
- styles/styleUat.css
fix: 更新樣式檔，修正急迫跑馬燈在滑鼠懸停或觸控時的動畫行為
> fix: 更新樣式檔，修正急迫跑馬燈在滑鼠懸停或觸控時的動畫行為

- index.html
- styles/style.css
fix: 更新主程式腳本版本參數，修正急迫跑馬燈在滑鼠懸停或觸控時的動畫行為
> fix: 更新主程式腳本版本參數，修正急迫跑馬燈在滑鼠懸停或觸控時的動畫行為

- 419ProtestEvent.html
- styles/419ProtestEvent.css
發現文字的部分因為寬度在手機版本會比螢幕還寬，因此會滑動，調整了一下文字顯示的排版
| | 修正前 | 修正後 | 
| ----------- | ----------- | ----------- |
| mob | ![photo_2025-04-18 16 21 21](https://github.com/user-attachments/assets/b7ad83cc-ba93-4e5a-a236-52f8942b1658) |<img width="344" alt="Screen Shot 2025-04-18 at 4 09 40 PM" src="https://github.com/user-attachments/assets/c273d77d-6632-424f-933b-cc966b9058d3" /> |
| pc |  <img width="1509" alt="Screen Shot 2025-04-18 at 4 26 48 PM" src="https://github.com/user-attachments/assets/842f4357-c313-40e9-989a-b6eee89db0b7" /> | <img width="1509" alt="Screen Shot 2025-04-18 at 4 09 57 PM" src="https://github.com/user-attachments/assets/9a35b79a-b921-4c5b-8b46-7c960f269e37" /> |
> fix: 修正419 info 樣式跑版

- styles/419ProtestEvent.css
> fix: 419 info 內容在pc 為置中顯示

- scripts/main.js
- styles/style.css
> fix: 修正樣式檔，優化滑鼠懸停時的動畫行為

- personData.json
> fix: 更新苗栗縣陳超明與邱鎮軍的開始日期及總天數

- 419ProtestEvent.html
- ckfinder.html
- complimentSquad.html
- index.html
- reasonsRecall.html
- video.html
> feat: 更新連署進度及活動標題，新增影片專區連結

- popup.json
> feat: 移除419守護台灣拒絕統戰活動資料

- index.html
- scripts/main.js
feat: 更新主程式以新增 Google Analytics 事件追蹤功能
> feat: 更新主程式以新增 Google Analytics 事件追蹤功能

- index.html
- scripts/fireworks.js
- scripts/main.js
- styles/style.css
> feat: 新增煙火效果並調整相關樣式及腳本引用

- scripts/fireworks.js
feat: 重構煙火效果程式碼，新增啟動與停止功能，並優化粒子管理
> feat: 重構煙火效果程式碼，新增啟動與停止功能，並優化粒子管理

- scripts/main.js
> fix: 更新收件狀態顯示文字，改善用戶體驗

- index.html
> fix: 暫時停用 popup.css 和js

- scripts/main.js
> fix: 移除花蓮縣傅崐萁的緊急提示代碼

- scripts/main.js
- styles/style.css
> feat: 更新進度條文字顯示及新增緊急跑馬燈動畫效果

- personData.json
> fix: 修正呂玉玲門檻數字

- index.html
- scripts/main.js
> fix: 修正進度條計算邏輯

- index.html
> fix: 暫時停用公告

- index.html
- scripts/main.js
fix: 調整篩選條件，將罷免人數範圍從15~30改為1~20
> fix: 調整篩選條件，將罷免人數範圍從15~30改為1~20

- 419ProtestEvent.html
- ckfinder.html
- complimentSquad.html
- index.html
- indexUat.html
- reasonsRecall.html
- video.html
> feat: 將浮動選單按鈕文字從「MENU」更改為「點我」

- index.html
- scripts/main.js
> feat: 更新通知內容，增加各罷團收件截止公告說明；調整篩選條件以顯示更多團隊

- index.html
- scripts/main.js
feat: 更新主程式邏輯，新增彰化縣謝衣鳳至篩選名單，調整篩選條件以顯示更多資料
> feat: 更新主程式邏輯，新增彰化縣謝衣鳳至篩選名單，調整篩選條件以顯示更多資料

- index.html
- scripts/main.js
> feat: 更新主程式邏輯，新增篩選條件以包含特定人員名稱

- index.html
- scripts/main.js
feat: 更新主程式邏輯，調整篩選條件以包含特定範圍的資料
> feat: 更新主程式邏輯，調整篩選條件以包含特定範圍的資料
